project:
  type: website

website:
  title: "AI in the Screen Sector: Case Studies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



