project:
  type: website

website:
  title: "AI in the Screen Sector: Casebook"
  navbar:
    logo: images/header-logos.png
    title: false
    right:
      - href: index.qmd
        text: Overview
      - href: case-studies/index.qmd
        text: Case studies
      - href: https://www.costarnetwork.co.uk/resources/ai-in-the-screen-sector-quarterly-digest-october-to-december-2025
        text: "Digest"

  page-footer:
    background: "#414141"
    left:
      - text: "costarnetwork.co.uk"
        href: https://www.costarnetwork.co.uk/labs/foresightlab
    center: Funded by [![](/images/ahrc-logo.png)](https://www.ukri.org/councils/ahrc/remit-programmes-and-priorities/convergent-screen-technologies-and-performance-in-realtime-costar/)
    right:
      - href: https://github.com/brtarran/ai-case-studies
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/showcase/costar-foresight-lab
        icon: linkedin
        aria-label: LinkedIn


format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



