project:
  type: website

website:
  title: "AI in the Screen Sector: Case Studies"
  navbar:
    logo: images/header-logos.png
    title: false
    right:
      - href: index.qmd
        text: Overview
      - href: case-studies/index.qmd
        text: Case studies

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



